/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Html } from '@react-three/drei'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/BillBoard.gltf')
  useFrame((state, delta) => (
    group.current.position.y = props.yOrigin + Math.sin(state.clock.getElapsedTime() * 1.1) / 8
  ))
  return (
    <group ref={group} {...props} dispose={null}>
      <Html transform position={[.1, 2.05, 0]} rotation={[0, 1.6, 0]} scale={[3, 3, 3]} className='billBoard' occlude >
        <div className='cube animate__animated animate__fadeIn'>
          <a href="https://github.com/BastingSumo" rel="noreferrer">GitHub</a><div></div>
          <a href="https://www.youtube.com/channel/UC3WBEpmhnvW3ILqzr9eDR5Q" rel="noreferrer">YouTube</a>
        </div >

      </Html>
      <group position={[0, 1.9, -0.02]} scale={[0.14, 0.65, 1.28]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.2266']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['Material.494']} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials['Material.660']} />
        <mesh geometry={nodes.Cube001_8.geometry} material={materials['Material.743']} />
        <mesh geometry={nodes.Cube001_9.geometry} material={materials['Material.826']} />
        <mesh geometry={nodes.Cube001_10.geometry} material={materials['Material.909']} />
        <mesh geometry={nodes.Cube001_11.geometry} material={materials['Material.992']} />
        <mesh geometry={nodes.Cube001_12.geometry} material={materials['Material.1241']} />
        <mesh geometry={nodes.Cube001_13.geometry} material={materials['Material.1324']} />
        <mesh geometry={nodes.Cube001_14.geometry} material={materials['Material.1656']} />
        <mesh geometry={nodes.Cube001_15.geometry} material={materials['Material.1739']} />
        <mesh geometry={nodes.Cube001_16.geometry} material={materials['Material.1822']} />
        <mesh geometry={nodes.Cube001_17.geometry} material={materials['Material.1988']} />
        <mesh geometry={nodes.Cube001_18.geometry} material={materials['Material.2237']} />
        <mesh geometry={nodes.Cube001_19.geometry} material={materials['Material.2262']} />
        <mesh geometry={nodes.Cube001_20.geometry} material={materials['Material.2264']} />
        <mesh geometry={nodes.Cube001_21.geometry} material={materials['Material.2265']} />
        <mesh geometry={nodes.Cube001_22.geometry} material={materials['Material.2261']} />
        <mesh geometry={nodes.Cube001_23.geometry} material={materials['Material.2267']} />
        <mesh geometry={nodes.Cube001_24.geometry} material={materials['Material.2278']} />
        <mesh geometry={nodes.Cube001_25.geometry} material={materials['Material.2279']} />
        <mesh geometry={nodes.Cube001_26.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_27.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/BillBoard.gltf')
