/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ResumeWebsite/deerF.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[0, 0.74, -0.66]} scale={[.15, .15, .15]}>
          <primitive object={nodes.Spine} />
          <primitive object={nodes.backlegIKL} />
          <primitive object={nodes.PullTargetBackL} />
          <primitive object={nodes.FrontlegIKL} />
          <primitive object={nodes.fronpulltargetL} />
          <primitive object={nodes.backlegIKR} />
          <primitive object={nodes.PullTargetBackR001} />
          <primitive object={nodes.FrontlegIKR} />
          <primitive object={nodes.fronpulltargetR} />
          <skinnedMesh geometry={nodes.Cube.geometry} material={materials.Material} skeleton={nodes.Cube.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ResumeWebsite/deerF.gltf')
