/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/FloatingIsland.gltf')
  const rotationAmount = 0.002
  useFrame((state, delta) => (group.current.rotation.y += props.rotationAmount))
  return (
    <group ref={group} {...props} dispose={null} scale={[.5, .5, .5]}>
      <group position={[-0.08, 0.2, 0.57]} rotation={[0, 0.95, 0]} scale={[0.06, 0.1, 0.06]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cube008_3.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube008_4.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cube008_5.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube008_6.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube008_7.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube008_8.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube008_9.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube008_10.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cube008_11.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Cube008_12.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube008_13.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Cube008_14.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube008_15.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Cube008_16.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Cube008_17.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Cube008_18.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Cube008_19.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Cube008_20.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Cube008_21.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Cube008_22.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Cube008_23.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Cube008_24.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube008_25.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Cube008_26.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube008_27.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube008_28.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Cube008_29.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Cube008_30.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Cube008_31.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cube008_32.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Cube008_33.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Cube008_34.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Cube008_35.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Cube008_36.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Cube008_37.geometry} material={materials['Material.055']} />
        <mesh geometry={nodes.Cube008_38.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Cube008_39.geometry} material={materials['Material.057']} />
        <mesh geometry={nodes.Cube008_40.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Cube008_41.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Cube008_42.geometry} material={materials['Material.060']} />
        <mesh geometry={nodes.Cube008_43.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.Cube008_44.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.Cube008_45.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.Cube008_46.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.Cube008_47.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Cube008_48.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.Cube008_49.geometry} material={materials['Material.067']} />
        <mesh geometry={nodes.Cube008_50.geometry} material={materials['Material.068']} />
        <mesh geometry={nodes.Cube008_51.geometry} material={materials['Material.069']} />
        <mesh geometry={nodes.Cube008_52.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.Cube008_53.geometry} material={materials['Material.071']} />
        <mesh geometry={nodes.Cube008_54.geometry} material={materials['Material.072']} />
        <mesh geometry={nodes.Cube008_55.geometry} material={materials['Material.073']} />
        <mesh geometry={nodes.Cube008_56.geometry} material={materials['Material.074']} />
        <mesh geometry={nodes.Cube008_57.geometry} material={materials['Material.075']} />
        <mesh geometry={nodes.Cube008_58.geometry} material={materials['Material.076']} />
        <mesh geometry={nodes.Cube008_59.geometry} material={materials['Material.077']} />
        <mesh geometry={nodes.Cube008_60.geometry} material={materials['Material.078']} />
        <mesh geometry={nodes.Cube008_61.geometry} material={materials['Material.079']} />
        <mesh geometry={nodes.Cube008_62.geometry} material={materials['Material.080']} />
        <mesh geometry={nodes.Cube008_63.geometry} material={materials['Material.081']} />
        <mesh geometry={nodes.Cube008_64.geometry} material={materials['Material.082']} />
        <mesh geometry={nodes.Cube008_65.geometry} material={materials['Material.083']} />
        <mesh geometry={nodes.Cube008_66.geometry} material={materials['Material.084']} />
        <mesh geometry={nodes.Cube008_67.geometry} material={materials['Material.098']} />
        <mesh geometry={nodes.Cube008_68.geometry} material={materials['Material.099']} />
        <mesh geometry={nodes.Cube008_69.geometry} material={materials['Material.102']} />
        <mesh geometry={nodes.Cube008_70.geometry} material={materials['Material.101']} />
        <mesh geometry={nodes.Cube008_71.geometry} material={materials['Material.100']} />
        <mesh geometry={nodes.Cube008_72.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Cube008_73.geometry} material={materials['Material.093']} />
        <mesh geometry={nodes.Cube008_74.geometry} material={materials['Material.092']} />
        <mesh geometry={nodes.Cube008_75.geometry} material={materials['Material.095']} />
        <mesh geometry={nodes.Cube008_76.geometry} material={materials['Material.097']} />
        <mesh geometry={nodes.Cube008_77.geometry} material={materials['Material.096']} />
        <mesh geometry={nodes.Cube008_78.geometry} material={materials['Material.103']} />
        <mesh geometry={nodes.Cube008_79.geometry} material={materials['Material.104']} />
        <mesh geometry={nodes.Cube008_80.geometry} material={materials['Material.105']} />
        <mesh geometry={nodes.Cube008_81.geometry} material={materials['Material.106']} />
        <mesh geometry={nodes.Cube008_82.geometry} material={materials['Material.107']} />
      </group>
    </group>
  )
}

useGLTF.preload('/FloatingIsland.gltf')
