/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFrame } from '@react-three/fiber'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ResumeWebsite/LittleHouse.gltf')
  useFrame((state, delta) => (group.current.rotation.y += 0.002))
  return (
    <group ref={group} {...props} dispose={null} scale={[.05, .05, .05]}>
      <group scale={0.81}>
        <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Icosphere_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Icosphere_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere_4.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Icosphere_5.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Icosphere_6.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Icosphere_7.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Icosphere_8.geometry} material={materials['Material.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ResumeWebsite/LittleHouse.gltf')
