/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Marcus.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh geometry={nodes.Body.geometry} material={materials['Material.001']} skeleton={nodes.Body.skeleton} />
          <skinnedMesh geometry={nodes.Boots.geometry} material={materials['Material.015']} skeleton={nodes.Boots.skeleton} />
          <skinnedMesh geometry={nodes.Pants.geometry} material={materials['Material.014']} skeleton={nodes.Pants.skeleton} />
          <skinnedMesh geometry={nodes.T_shirt.geometry} material={materials['Material.006']} skeleton={nodes.T_shirt.skeleton} />
        </group>
        <group name="mixamoCube" rotation={[Math.PI, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/Marcus.gltf')
