/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFrame } from '@react-three/fiber'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ResumeWebsite/MinerIsland.gltf')
  const { actions } = useAnimations(animations, group)
  useFrame((state, delta) => (
    group.current.position.y = props.yOrigin + Math.sin(state.clock.getElapsedTime()) / 8,
    group.current.rotation.y += .6 * delta
  ))
  return (
    <group ref={group} {...props} dispose={null} scale={[.1, .1, .1]}>
      <group>
        <group name="mixamoCube" rotation={[Math.PI, 0, 0]} scale={100} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh geometry={nodes.Body.geometry} material={materials['Material.005']} skeleton={nodes.Body.skeleton} />
          <skinnedMesh geometry={nodes.Boots.geometry} material={materials['Material.015']} skeleton={nodes.Boots.skeleton} />
          <skinnedMesh geometry={nodes.Pants.geometry} material={materials['Material.008']} skeleton={nodes.Pants.skeleton} />
          <skinnedMesh geometry={nodes.T_shirt.geometry} material={materials['Material.006']} skeleton={nodes.T_shirt.skeleton} />
          <skinnedMesh geometry={nodes.vest.geometry} material={materials['Material.001']} skeleton={nodes.vest.skeleton} />
        </group>
        <group position={[-0.08, 0.56, 1.09]} scale={0.09}>
          <mesh geometry={nodes.Icosphere006_1.geometry} material={materials['Material.181']} />
          <mesh geometry={nodes.Icosphere006_2.geometry} material={materials['Material.168']} />
          <mesh geometry={nodes.Icosphere006_3.geometry} material={materials['Material.176']} />
          <mesh geometry={nodes.Icosphere006_4.geometry} material={materials['Material.177']} />
          <mesh geometry={nodes.Icosphere006_5.geometry} material={materials['Material.178']} />
          <mesh geometry={nodes.Icosphere006_6.geometry} material={materials['Material.179']} />
          <mesh geometry={nodes.Icosphere006_7.geometry} material={materials['Material.182']} />
          <mesh geometry={nodes.Icosphere006_8.geometry} material={materials['Material.183']} />
          <mesh geometry={nodes.Icosphere006_9.geometry} material={materials['Material.184']} />
          <mesh geometry={nodes.Icosphere006_10.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Icosphere006_11.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Icosphere006_12.geometry} material={materials['Material.022']} />
          <mesh geometry={nodes.Icosphere006_13.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.Icosphere006_14.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Icosphere006_15.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Icosphere006_16.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Icosphere006_17.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Icosphere006_18.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes.Icosphere006_19.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Icosphere006_20.geometry} material={materials['Material.018']} />
          <mesh geometry={nodes.Icosphere006_21.geometry} material={materials['Material.028']} />
          <mesh geometry={nodes.Icosphere006_22.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Icosphere006_23.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.Icosphere006_24.geometry} material={materials['Material.027']} />
          <mesh geometry={nodes.Icosphere006_25.geometry} material={materials['Material.029']} />
          <mesh geometry={nodes.Icosphere006_26.geometry} material={materials['Material.030']} />
          <mesh geometry={nodes.Icosphere006_27.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Icosphere006_28.geometry} material={materials['Material.032']} />
          <mesh geometry={nodes.Icosphere006_29.geometry} material={materials['Material.037']} />
          <mesh geometry={nodes.Icosphere006_30.geometry} material={materials['Material.038']} />
          <mesh geometry={nodes.Icosphere006_31.geometry} material={materials['Material.039']} />
          <mesh geometry={nodes.Icosphere006_32.geometry} material={materials['Material.040']} />
          <mesh geometry={nodes.Icosphere006_33.geometry} material={materials['Material.041']} />
          <mesh geometry={nodes.Icosphere006_34.geometry} material={materials['Material.042']} />
          <mesh geometry={nodes.Icosphere006_35.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.Icosphere006_36.geometry} material={materials['Material.044']} />
          <mesh geometry={nodes.Icosphere006_37.geometry} material={materials['Material.045']} />
          <mesh geometry={nodes.Icosphere006_38.geometry} material={materials['Material.046']} />
          <mesh geometry={nodes.Icosphere006_39.geometry} material={materials['Material.047']} />
          <mesh geometry={nodes.Icosphere006_40.geometry} material={materials['Material.048']} />
          <mesh geometry={nodes.Icosphere006_41.geometry} material={materials['Material.049']} />
          <mesh geometry={nodes.Icosphere006_42.geometry} material={materials['Material.050']} />
          <mesh geometry={nodes.Icosphere006_43.geometry} material={materials['Material.051']} />
          <mesh geometry={nodes.Icosphere006_44.geometry} material={materials['Material.052']} />
          <mesh geometry={nodes.Icosphere006_45.geometry} material={materials['Material.053']} />
          <mesh geometry={nodes.Icosphere006_46.geometry} material={materials['Material.054']} />
          <mesh geometry={nodes.Icosphere006_47.geometry} material={materials['Material.055']} />
          <mesh geometry={nodes.Icosphere006_48.geometry} material={materials['Material.056']} />
          <mesh geometry={nodes.Icosphere006_49.geometry} material={materials['Material.057']} />
          <mesh geometry={nodes.Icosphere006_50.geometry} material={materials['Material.058']} />
          <mesh geometry={nodes.Icosphere006_51.geometry} material={materials['Material.059']} />
          <mesh geometry={nodes.Icosphere006_52.geometry} material={materials['Material.060']} />
          <mesh geometry={nodes.Icosphere006_53.geometry} material={materials['Material.061']} />
          <mesh geometry={nodes.Icosphere006_54.geometry} material={materials['Material.062']} />
          <mesh geometry={nodes.Icosphere006_55.geometry} material={materials['Material.063']} />
          <mesh geometry={nodes.Icosphere006_56.geometry} material={materials['Material.064']} />
          <mesh geometry={nodes.Icosphere006_57.geometry} material={materials['Material.065']} />
          <mesh geometry={nodes.Icosphere006_58.geometry} material={materials['Material.066']} />
          <mesh geometry={nodes.Icosphere006_59.geometry} material={materials['Material.067']} />
          <mesh geometry={nodes.Icosphere006_60.geometry} material={materials['Material.068']} />
          <mesh geometry={nodes.Icosphere006_61.geometry} material={materials['Material.069']} />
          <mesh geometry={nodes.Icosphere006_62.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Icosphere006_63.geometry} material={materials['Material.071']} />
          <mesh geometry={nodes.Icosphere006_64.geometry} material={materials['Material.072']} />
          <mesh geometry={nodes.Icosphere006_65.geometry} material={materials['Material.073']} />
          <mesh geometry={nodes.Icosphere006_66.geometry} material={materials['Material.074']} />
          <mesh geometry={nodes.Icosphere006_67.geometry} material={materials['Material.075']} />
          <mesh geometry={nodes.Icosphere006_68.geometry} material={materials['Material.076']} />
          <mesh geometry={nodes.Icosphere006_69.geometry} material={materials['Material.077']} />
          <mesh geometry={nodes.Icosphere006_70.geometry} material={materials['Material.078']} />
          <mesh geometry={nodes.Icosphere006_71.geometry} material={materials['Material.079']} />
          <mesh geometry={nodes.Icosphere006_72.geometry} material={materials['Material.080']} />
          <mesh geometry={nodes.Icosphere006_73.geometry} material={materials['Material.081']} />
          <mesh geometry={nodes.Icosphere006_74.geometry} material={materials['Material.082']} />
          <mesh geometry={nodes.Icosphere006_75.geometry} material={materials['Material.083']} />
          <mesh geometry={nodes.Icosphere006_76.geometry} material={materials['Material.084']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ResumeWebsite/MinerIsland.gltf')
