/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ResumeWebsite/Missile.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={[.5, .5, .5]}>
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['Material.006']} />
    </group>
  )
}

useGLTF.preload('/ResumeWebsite/Missile.gltf')
