/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ResumeWebsite/MusketMan.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={[.0014, .0014, .0014]}>
      <group>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} >
          <primitive object={nodes.mixamorigHips} />
          <mesh geometry={nodes.Pants002.geometry} material={materials['Material.023']} position={[1.9, -4.98, 3.56]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 106.16]} />
          <group>
            <skinnedMesh geometry={nodes.Cube001.geometry} material={materials['Material.014']} skeleton={nodes.Cube001.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_1.geometry} material={materials['Material.006']} skeleton={nodes.Cube001_1.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_2.geometry} material={materials['Material.005']} skeleton={nodes.Cube001_2.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_3.geometry} material={materials['Material.004']} skeleton={nodes.Cube001_3.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_4.geometry} material={materials['Material.003']} skeleton={nodes.Cube001_4.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_5.geometry} material={materials['Material.002']} skeleton={nodes.Cube001_5.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_6.geometry} material={materials['Material.016']} skeleton={nodes.Cube001_6.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_7.geometry} material={materials['Material.001']} skeleton={nodes.Cube001_7.skeleton} />
            <skinnedMesh geometry={nodes.Cube001_8.geometry} material={materials['Material.015']} skeleton={nodes.Cube001_8.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ResumeWebsite/MusketMan.gltf')
