/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/PCSetupIsland.gltf')
  useFrame((state, delta) => (
    group.current.position.y = props.yOrigin + Math.sin(state.clock.getElapsedTime()) / 8,
    group.current.rotation.y += .6 * delta
  ))
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.33, 0.24, -0.25]} rotation={[-0.74, -0.12, -1.46]} scale={0.1}>
        <mesh geometry={nodes.Icosphere004.geometry} material={materials['Material.2266']} />
        <mesh geometry={nodes.Icosphere004_1.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Icosphere004_2.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Icosphere004_3.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Icosphere004_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Icosphere004_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Icosphere004_6.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere004_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Icosphere004_8.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Icosphere004_9.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Icosphere004_10.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Icosphere004_11.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Icosphere004_12.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Icosphere004_13.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Icosphere004_14.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Icosphere004_15.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Icosphere004_16.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Icosphere004_17.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Icosphere004_18.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Icosphere004_19.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Icosphere004_20.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Icosphere004_21.geometry} material={materials['Material.085']} />
        <mesh geometry={nodes.Icosphere004_22.geometry} material={materials['Material.494']} />
        <mesh geometry={nodes.Icosphere004_23.geometry} material={materials['Material.660']} />
        <mesh geometry={nodes.Icosphere004_24.geometry} material={materials['Material.743']} />
        <mesh geometry={nodes.Icosphere004_25.geometry} material={materials['Material.826']} />
        <mesh geometry={nodes.Icosphere004_26.geometry} material={materials['Material.909']} />
        <mesh geometry={nodes.Icosphere004_27.geometry} material={materials['Material.992']} />
        <mesh geometry={nodes.Icosphere004_28.geometry} material={materials['Material.1241']} />
        <mesh geometry={nodes.Icosphere004_29.geometry} material={materials['Material.1324']} />
        <mesh geometry={nodes.Icosphere004_30.geometry} material={materials['Material.1656']} />
        <mesh geometry={nodes.Icosphere004_31.geometry} material={materials['Material.1739']} />
        <mesh geometry={nodes.Icosphere004_32.geometry} material={materials['Material.1822']} />
        <mesh geometry={nodes.Icosphere004_33.geometry} material={materials['Material.1988']} />
        <mesh geometry={nodes.Icosphere004_34.geometry} material={materials['Material.2237']} />
        <mesh geometry={nodes.Icosphere004_35.geometry} material={materials['Material.2262']} />
        <mesh geometry={nodes.Icosphere004_36.geometry} material={materials['Material.2264']} />
        <mesh geometry={nodes.Icosphere004_37.geometry} material={materials['Material.2265']} />
        <mesh geometry={nodes.Icosphere004_38.geometry} material={materials['Material.2261']} />
        <mesh geometry={nodes.Icosphere004_39.geometry} material={materials['Material.2267']} />
        <mesh geometry={nodes.Icosphere004_40.geometry} material={materials['Material.2278']} />
        <mesh geometry={nodes.Icosphere004_41.geometry} material={materials['Material.2279']} />
        <mesh geometry={nodes.Icosphere004_42.geometry} material={materials['Material.2361']} />
        <mesh geometry={nodes.Icosphere004_43.geometry} material={materials['Material.2362']} />
        <mesh geometry={nodes.Icosphere004_44.geometry} material={materials['Material.2444']} />
        <mesh geometry={nodes.Icosphere004_45.geometry} material={materials['Material.2445']} />
      </group>
      <group position={[0.08, 0.48, -0.04]} rotation={[Math.PI, -1.09, Math.PI]} scale={0.03}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.2601']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.2602']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.2603']} position={[0.08, 0.51, -0.05]} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/PCSetupIsland.gltf')
