/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ResumeWebsite/TwoStory.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={.1}>
      <group position={[4.39, 3.57, 0.16]} rotation={[0, 1.57, 0]} scale={[0.16, 0.03, 0.01]}>
        <mesh geometry={nodes.Cube229.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube229_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube229_2.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Cube229_3.geometry} material={materials['Material.169']} />
        <mesh geometry={nodes.Cube229_4.geometry} material={materials['Material.031']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ResumeWebsite/TwoStory.gltf')
