/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/WoodHouseWoodRoof.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={[.1, .1, .1]}>
      <group position={[0, -0.1, 0]} scale={[6.5, 0.23, 4.6]}>
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials['Material.083']} />
        <mesh geometry={nodes.Icosphere_2.geometry} material={materials['Material.507']} />
        <mesh geometry={nodes.Icosphere_3.geometry} material={materials['Material.506']} />
        <mesh geometry={nodes.Icosphere_4.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.Icosphere_5.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/WoodHouseWoodRoof.gltf')
